future: true
permalink: /:title/
url: http://Evene.github.io
name: LiuFang
author: LiuFang
qq: yourqq
email: 3194721855@qq.com

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: yourID
about: "这里是 Your 的个人博客，创建于 20xx 年。"

safe: true
paginate: 20
